### ISSUE TITLE
Esc makes the tip disappears but it keeps coming back afterward

### ISSUE THREAD

**Issue by PierreR** [flycheck/flycheck-pos-tip#7]
When I press `Esc` (or `c-g`), the tooltip disappears as expected. Unfortunately  (if I leave my cursor at the same position) the tip is coming back after a few seconds which is never what I wish for.

Is there another way to quickly dismiss the tip (without changing the cursor position) ?

I hope this is the right place to submit such issue (or should it go more upstream ?)

Thanks for your support.

PS: I am using spacemacs (develop branch).

**Comment by lunaryorn** [comment]
@PierreR Neither `Esc` nor `C-g`—these are different commands in Spacemacs, by the way—should hide the tooltip.   They do only by accident, because they trigger `post-command-hook` which in turn restarts Flycheck's error display.  Since Flycheck currently doesn't check whether point moved in between, you see'll see the tooltip being redisplayed immediately.

The issue itself should be fixed in Flycheck, but to me that's a very small edge case and a very low priority issue.  I've opened https://github.com/flycheck/flycheck/issues/788, but don't expect me to fix that any time soon.  There's much more important stuff to do in Flycheck. 

Closing as invalid, since it's a Flycheck issue.
